<a href="https://colab.research.google.com/github/ananyakaligal/Deep-Learning-Notes/blob/main/Activation_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import math

def basic_sigmoid(x):
    s = 1/(1+math.exp(-x))
    return s

basic_sigmoid(-1)

0.2689414213699951

In [10]:
#Example of vector operation

import numpy as np

x=np.array([1,2,3])
print(np.exp(x))
print(x+3)

[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


In [16]:
#GRADED FUNCTION: sigmoid

import numpy as np

def sigmoid(x):
  s=1/(1+np.exp(-x))
  return s

x=np.array([1,2,3])
y=sigmoid(x)
y

array([0.73105858, 0.88079708, 0.95257413])

In [19]:
def sigmoid_derivative(y):
  return y*(1-y)

sigmoid_derivative(y)

array([0.19661193, 0.10499359, 0.04517666])

In [25]:
#Graded function : image2vector

def image2vector(image):
  length,height,depth=image.shape
  return image.reshape(length*height*depth,1)

image2vector(np.array([[[0.67826139,0.29380381],[.90714982,0.52835647],[0.4515251,.45097551]],[[0.645826139,0.78380381],[.67714982,0.12835647],[0.26615251,.55017551]],[[0.5826139,0.2953380381],[.90714982,0.52835647],[0.4215251,.45017551]]]))

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4515251 ],
       [0.45097551],
       [0.64582614],
       [0.78380381],
       [0.67714982],
       [0.12835647],
       [0.26615251],
       [0.55017551],
       [0.5826139 ],
       [0.29533804],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551]])